# Generated by Django 3.0.5 on 2020-05-15 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regionInfo1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture', models.CharField(max_length=100)),
                ('population', models.IntegerField(default=0)),
                ('annualIncome', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='station1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertOfStation', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('setFee', models.IntegerField(default=0)),
                ('FreeFee', models.IntegerField(default=0)),
                ('destanceToStation', models.IntegerField(default=0)),
                ('eventTimes', models.IntegerField(default=0)),
                ('mjTables', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.regionInfo1')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.station1')),
            ],
        ),
    ]
