# Generated by Django 3.0.5 on 2020-05-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regioninfo1',
            name='cityName',
            field=models.CharField(default='横浜', max_length=100),
        ),
        migrations.AddField(
            model_name='station1',
            name='stationName',
            field=models.CharField(default='横浜駅', max_length=100),
        ),
    ]
